### ISSUE TITLE
Nx run many list empty on lunarvim

### ISSUE THREAD

**Issue by CinematicCow** [Equilibris/nx.nvim#14] opened 2023-06-09 12:25 UTC
**Describe the bug**
Apart from generators, all the commands, i.e. `:Telescope nx <command>` are returning empty and throwing nil errors.

**To Reproduce**
1. Go to ':Telescope nx run_many'
2. Type '-t serve -p web'
3. Press enter
4. See error `rror executing Lua callback: ...e/pack/lazy/opt/telescope.nvim/lua/telescope/command.lua:183: attempt to call a nil value`

**Expected behavior**
Should run the executed command and run/serve the web version of the project, in this case a next application.

**Screenshots**
![image](https://github.com/Equilibris/nx.nvim/assets/26029731/aa809421-ca8a-4917-8620-3e16971455c3)
![image](https://github.com/Equilibris/nx.nvim/assets/26029731/36240658-8089-4893-a3ff-ca7a965f0c0d)

**Desktop:**
 - OS: Pop_os 22.04 LTS
 - Neovim: v0.9.1
 - Lunarvim: v1.3

**Additional context**

**Comment by Equilibris** [comment] 2023-08-01 21:24
Please test and report back if it works

**Comment by Equilibris** [comment] 2023-08-06 09:08
Hi this should be fixed. Please ensure that it is. If I don't get a response within 3 days I will assume the issue is fixed and close it as the bug matches #9 which has since been patched

**Closed** 2023-08-14 20:23 UTC
